"""Oracle APEX DDL SQL -> BESSER B-UML DomainModel parser.

Parses the ``script.sql`` (or any Oracle DDL file) that accompanies an Oracle
APEX exported application and builds a BESSER B-UML DomainModel from it.

The DDL format produced by Oracle APEX SQL exports uses:
  - ``NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`` for surrogate PKs
  - ``VARCHAR2(N)`` / ``NUMBER`` / ``DATE`` / ``TIMESTAMP`` for column types
  - Separate ``FOREIGN KEY (col) REFERENCES table(col)`` constraints  OR
    inline ``REFERENCES table(col)`` at the end of a column definition
  - ``ALTER TABLE ... ADD FOREIGN KEY`` for cross-table FK constraints

All auto-generated surrogate primary key columns (IDENTITY) are skipped.
Foreign key columns are converted to B-UML BinaryAssociations instead of
plain attributes.

oracle_apex_to_buml(ddl_path, module_name) is the single entry point and
accepts either:
  - a path to one ``.sql`` DDL file, or
  - a path to a folder containing ``.sql`` DDL files, which are
    auto-discovered, skipping non-DDL scripts (deinstall, data-load,
    PL/SQL packages, APEX app exports, etc.) and deduplicating tables that
    appear in more than one file.

Multi-file support (used internally, also available directly):
    oracle_apex_multi_to_buml(paths, module_name)
        Accepts a list of .sql file paths, merges them, and parses as one.

    oracle_apex_dir_to_buml(folder, module_name)
        Auto-discovers DDL .sql files in a folder and merges them.

Usage:
    from migrator.parsers.oracle_apex.oracle_apex import oracle_apex_to_buml

    domain_model = oracle_apex_to_buml("script.sql", module_name="LibraryApp")
    domain_model = oracle_apex_to_buml("path/to/sql/folder", module_name="MyApp")
"""

import glob
import os
import re
import tempfile

from besser.BUML.metamodel.structural import (
    BinaryAssociation,
    BooleanType,
    Class,
    DateTimeType,
    DateType,
    DomainModel,
    FloatType,
    IntegerType,
    Multiplicity,
    Property,
    StringType,
)

# ---------------------------------------------------------------------------
# Oracle -> B-UML type mapping
# ---------------------------------------------------------------------------

_ORACLE_TYPE_MAP = {
    "VARCHAR2":      StringType,
    "NVARCHAR2":     StringType,
    "VARCHAR":       StringType,
    "CHAR":          StringType,
    "NCHAR":         StringType,
    "CLOB":          StringType,
    "NCLOB":         StringType,
    "LONG":          StringType,
    "NUMBER":        IntegerType,
    "INTEGER":       IntegerType,
    "INT":           IntegerType,
    "SMALLINT":      IntegerType,
    "FLOAT":         FloatType,
    "BINARY_FLOAT":  FloatType,
    "BINARY_DOUBLE": FloatType,
    "DECIMAL":       FloatType,
    "NUMERIC":       FloatType,
    "DATE":          DateType,
    "TIMESTAMP":     DateTimeType,
    "BOOLEAN":       BooleanType,
}

# ---------------------------------------------------------------------------
# Regex patterns
# ---------------------------------------------------------------------------

# Handles both ; and / terminators, optional double-quoted table names
_CREATE_TABLE_RE = re.compile(
    r'CREATE\s+TABLE\s+"?(\w+)"?\s*\((.*?)\)\s*(?:;|/)',
    re.IGNORECASE | re.DOTALL,
)

# ALTER TABLE ... ADD [CONSTRAINT name] FOREIGN KEY (col) REFERENCES other(col)
_ALTER_FK_RE = re.compile(
    r'ALTER\s+TABLE\s+"?(\w+)"?\s+ADD\s+(?:CONSTRAINT\s+"?\w+"?\s+)?'
    r'FOREIGN\s+KEY\s*\(\s*"?(\w+)"?\s*\)\s+REFERENCES\s+"?(\w+)"?',
    re.IGNORECASE,
)

# IDENTITY / auto-increment PK columns — skip these
_IDENTITY_RE = re.compile(r"GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY", re.IGNORECASE)

# Standalone FOREIGN KEY constraint inside a CREATE TABLE body
_FK_CONSTRAINT_RE = re.compile(
    r"FOREIGN\s+KEY\s*\(\s*(\w+)\s*\)\s+REFERENCES\s+(\w+)\s*\(\s*\w+\s*\)",
    re.IGNORECASE,
)

# Column definition: name + type + optional size + optional NOT NULL + optional inline REFERENCES
_COLUMN_RE = re.compile(
    r'^"?(\w+)"?\s+'
    r'(VARCHAR2|NVARCHAR2|VARCHAR|CHAR|NCHAR|CLOB|NCLOB'
    r'|LONG|NUMBER|INTEGER|INT|SMALLINT|FLOAT'
    r'|BINARY_FLOAT|BINARY_DOUBLE|DECIMAL|NUMERIC'
    r'|DATE|TIMESTAMP|BOOLEAN)'
    r'(?:\s*\([^)]+\))?'
    r'(?:\s+NOT\s+NULL)?'
    r'(?:\s+REFERENCES\s+(\w+)\s*\(\s*\w+\s*\))?',
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _to_pascal(name: str) -> str:
    """Convert snake_case or UPPER_CASE to PascalCase."""
    return "".join(word.capitalize() for word in name.lower().split("_"))


def _collect_alter_fks(content: str) -> dict:
    """Pre-collect ALTER TABLE FK columns: {table_lower: {col_lower, ...}}"""
    result: dict = {}
    for m in _ALTER_FK_RE.finditer(content):
        result.setdefault(m.group(1).lower(), set()).add(m.group(2).lower())
    return result


def _collect_inline_fks(table_body: str) -> dict:
    """Return {fk_col: ref_table} from FK constraints inside a CREATE TABLE body."""
    fk_map: dict = {}
    for line in table_body.splitlines():
        line = line.strip().rstrip(",")
        m = _FK_CONSTRAINT_RE.match(line)
        if m:
            fk_map[m.group(1).lower()] = m.group(2).lower()
            continue
        m2 = _COLUMN_RE.match(line)
        if m2 and m2.group(3):
            fk_map[m2.group(1).lower()] = m2.group(3).lower()
    return fk_map


def _parse_columns(table_body: str, fk_columns: set) -> set:
    """Parse column definitions; return a set of Properties (FK cols excluded)."""
    properties: set = set()
    for line in table_body.splitlines():
        line = line.strip().rstrip(",")
        if not line or line.upper().startswith(("--", "/*")):
            continue
        if _IDENTITY_RE.search(line):
            continue
        if re.match(r"(PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT)\b", line, re.IGNORECASE):
            continue
        if re.match(r"USING\s+INDEX\b", line, re.IGNORECASE):
            continue
        m = _COLUMN_RE.match(line)
        if not m:
            continue
        col_name = m.group(1).lower()
        type_str = m.group(2).upper()
        if col_name in fk_columns:
            continue
        buml_type = _ORACLE_TYPE_MAP.get(type_str, StringType)
        min_mult  = 1 if re.search(r"\bNOT\s+NULL\b", line, re.IGNORECASE) else 0
        properties.add(Property(name=col_name, type=buml_type,
                                multiplicity=Multiplicity(min_mult, 1)))
    return properties


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def oracle_apex_to_buml(ddl_path: str, module_name: str = None,
                         pattern: str = "*.sql") -> DomainModel:
    """Parse Oracle APEX DDL SQL and return a BESSER B-UML DomainModel.

    Accepts either a single ``.sql`` file or a folder containing DDL ``.sql``
    files. Folders are handled via :func:`oracle_apex_dir_to_buml`, which
    discovers and merges the relevant DDL files automatically.

    Args:
        ddl_path:    Path to a DDL ``.sql`` file, or a folder containing them.
        module_name: Optional name for the resulting DomainModel.
        pattern:     Glob pattern used when ``ddl_path`` is a folder
                     (default ``"*.sql"``).

    Returns:
        A populated ``DomainModel``, or ``None`` on a fatal error.
    """
    if os.path.isdir(ddl_path):
        return oracle_apex_dir_to_buml(ddl_path, module_name=module_name,
                                        pattern=pattern)
    return _oracle_apex_file_to_buml(ddl_path, module_name=module_name)


def _oracle_apex_file_to_buml(ddl_path: str, module_name: str = None) -> DomainModel:
    """Parse a single Oracle APEX DDL SQL file and return a DomainModel.

    Args:
        ddl_path:    Path to the DDL ``.sql`` file.
        module_name: Optional name for the resulting DomainModel.

    Returns:
        A populated ``DomainModel``, or ``None`` on a fatal error.
    """
    if not os.path.exists(ddl_path):
        print(f"File not found: {ddl_path}")
        return None
    if os.path.getsize(ddl_path) == 0:
        print(f"File is empty: {ddl_path}")
        return None

    with open(ddl_path, "r", encoding="utf-8", errors="replace") as fh:
        content = fh.read()

    name         = module_name or os.path.splitext(os.path.basename(ddl_path))[0]
    domain_model = DomainModel(name=name)
    classes:      dict = {}
    pending_fks:  list = []

    print(f"Parsing Oracle APEX DDL: {os.path.basename(ddl_path)}")

    # Two-pass: pre-collect ALTER TABLE FK columns so they are excluded
    # from class attributes (same behaviour as inline FKs)
    alter_fk_cols = _collect_alter_fks(content)

    for match in _CREATE_TABLE_RE.finditer(content):
        table_key  = match.group(1).lower()
        table_body = match.group(2)
        class_name = _to_pascal(table_key)

        inline_fks  = _collect_inline_fks(table_body)
        all_fk_cols = set(inline_fks.keys()) | alter_fk_cols.get(table_key, set())

        for fk_col, ref_table in inline_fks.items():
            pending_fks.append((table_key, fk_col, ref_table))

        properties = _parse_columns(table_body, all_fk_cols)
        cls        = Class(name=class_name, attributes=properties)
        classes[table_key] = cls
        domain_model.types.add(cls)
        print(f"  Class '{class_name}': {sorted(p.name for p in properties)}")

    # Add ALTER TABLE FKs to the pending list
    for m in _ALTER_FK_RE.finditer(content):
        pending_fks.append((m.group(1).lower(), m.group(2).lower(), m.group(3).lower()))

    # Build BinaryAssociations
    assoc_counter: dict = {}
    for from_table, fk_col, to_table in pending_fks:
        if from_table not in classes or to_table not in classes:
            print(f"  Skipping FK '{from_table}.{fk_col}' -> unknown table '{to_table}'")
            continue
        from_cls = classes[from_table]
        to_cls   = classes[to_table]

        # Self-referencing FK: use column name as suffix to keep end names unique
        if from_cls.name == to_cls.name:
            end_one_name = f"{to_cls.name.lower()}_{fk_col}"
        else:
            key   = (from_table, to_table)
            count = assoc_counter.get(key, 0)
            assoc_counter[key] = count + 1
            end_one_name = to_cls.name.lower() if count == 0 else f"{to_cls.name.lower()}_{count}"

        end_many = Property(name=from_cls.name.lower(), type=from_cls,
                            multiplicity=Multiplicity(0, "*"))
        end_one  = Property(name=end_one_name, type=to_cls,
                            multiplicity=Multiplicity(0, 1))
        domain_model.associations.add(
            BinaryAssociation(name=f"{from_cls.name}_{to_cls.name}",
                              ends={end_many, end_one})
        )

    print(f"  Total: {len(classes)} classes, {len(domain_model.associations)} associations")
    return domain_model


# ---------------------------------------------------------------------------
# Multi-file helpers
# ---------------------------------------------------------------------------

# Patterns that identify NON-DDL / non-schema SQL files to skip automatically
_SKIP_NAME_RE = re.compile(
    r"(deinstall|load[_-]?data|insert[_-]?data|seed|"
    r"[_-]pkg[_-]|pkg[_-]body|pkg[_-]spec|"
    r"trigger|timing|process[_-]table|"
    r"set[_-]?plscope|load[_-]?sample|"
    r"summary|^scope\.|^start\.|"
    r"refresh[_-]?data|update[_-]?data|drop[_-]?old|"
    r"pipelined|event[_-]?log|event[_-]?pkg|"
    r"sequence\.sql)",
    re.IGNORECASE,
)

# APEX monolithic app exports always contain this token
_APEX_EXPORT_TOKEN = re.compile(r"wwv_flow_imp\.import_begin", re.IGNORECASE)

# Used to detect duplicate CREATE TABLE definitions across files
_TABLE_NAME_RE = re.compile(r'CREATE\s+TABLE\s+"?(\w+)"?\s*\(', re.IGNORECASE)


def _is_ddl_file(path: str) -> bool:
    """Return True if the file looks like a DDL schema file worth parsing."""
    name = os.path.basename(path)
    if _SKIP_NAME_RE.search(name):
        return False
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            head = fh.read(2048)
        if _APEX_EXPORT_TOKEN.search(head):
            return False
    except OSError:
        return False
    return True


def _merge_ddl_files(paths: list) -> str:
    """Concatenate multiple DDL files, skipping duplicate CREATE TABLE blocks."""
    seen_tables: set = set()
    parts = []
    for p in paths:
        with open(p, "r", encoding="utf-8", errors="replace") as fh:
            content = fh.read()
        tables_in_file = {m.group(1).upper() for m in _TABLE_NAME_RE.finditer(content)}
        duplicates = tables_in_file & seen_tables
        if duplicates:
            print(f"  Skipping {os.path.basename(p)} (duplicate tables: {sorted(duplicates)})")
            continue
        seen_tables.update(tables_in_file)
        parts.append(content)
        parts.append("\n")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Multi-file entry points
# ---------------------------------------------------------------------------

def oracle_apex_multi_to_buml(paths: list, module_name: str = None):
    """Parse multiple Oracle APEX DDL SQL files and return a DomainModel.

    All files are merged (with duplicate-table deduplication) and parsed as
    a single DDL document.

    Args:
        paths      : list of paths to .sql DDL files (merged in given order).
        module_name: optional name for the resulting DomainModel.

    Returns:
        A populated DomainModel, or None on a fatal error.
    """
    if not paths:
        print("oracle_apex_multi_to_buml: no files provided.")
        return None

    missing = [p for p in paths if not os.path.isfile(p)]
    if missing:
        for p in missing:
            print(f"  File not found: {p}")
        return None

    print(f"Merging {len(paths)} DDL file(s):")
    for p in paths:
        print(f"  + {os.path.basename(p)}")

    combined = _merge_ddl_files(paths)
    name = module_name or "OracleApexModel"

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".sql", encoding="utf-8", delete=False
    ) as tmp:
        tmp.write(combined)
        tmp_path = tmp.name

    try:
        model = _oracle_apex_file_to_buml(ddl_path=tmp_path, module_name=name)
    finally:
        os.unlink(tmp_path)

    return model


def oracle_apex_dir_to_buml(folder: str, module_name: str = None,
                             pattern: str = "*.sql"):
    """Discover DDL .sql files in a folder, merge them, and return a DomainModel.

    Non-DDL files (deinstall scripts, data-load scripts, APEX app exports,
    PL/SQL packages, triggers, etc.) are skipped automatically.  Duplicate
    CREATE TABLE definitions across files are also deduplicated.

    Args:
        folder     : directory to search for .sql files (searched recursively).
        module_name: optional name for the resulting DomainModel.
        pattern    : glob pattern for SQL files (default "*.sql").

    Returns:
        A populated DomainModel, or None on a fatal error.
    """
    if not os.path.isdir(folder):
        print(f"oracle_apex_dir_to_buml: folder not found: {folder}")
        return None

    all_sql = sorted(glob.glob(os.path.join(folder, "**", pattern), recursive=True))
    ddl_files = [p for p in all_sql if _is_ddl_file(p)]

    if not ddl_files:
        print(f"oracle_apex_dir_to_buml: no DDL files found in: {folder}")
        return None

    return oracle_apex_multi_to_buml(ddl_files, module_name=module_name)
