"""Oracle APEX DDL SQL → BESSER B-UML DomainModel parser.

Parses the ``script.sql`` (or any Oracle DDL file) that accompanies an Oracle
APEX exported application and builds a BESSER B-UML DomainModel from it.

The DDL format produced by Oracle APEX SQL exports uses:
  - ``NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`` for surrogate PKs
  - ``VARCHAR2(N)`` / ``NUMBER`` / ``DATE`` / ``TIMESTAMP`` for column types
  - Separate ``FOREIGN KEY (col) REFERENCES table(col)`` constraints  OR
    inline ``REFERENCES table(col)`` at the end of a column definition

All auto-generated surrogate primary key columns (IDENTITY) are skipped.
Foreign key columns are converted to B-UML BinaryAssociations instead of
plain attributes.

Usage:
    from migrator.parsers.oracle_apex import oracle_apex_to_buml
    domain_model = oracle_apex_to_buml("script.sql", module_name="LibraryApp")
"""

import os
import re

from besser.BUML.metamodel.structural import (
    BinaryAssociation,
    BooleanType,
    Class,
    DateTimeType,
    DateType,
    DomainModel,
    FloatType,
    IntegerType,
    Multiplicity,
    Property,
    StringType,
)

# ---------------------------------------------------------------------------
# Oracle → B-UML type mapping
# ---------------------------------------------------------------------------

_ORACLE_TYPE_MAP = {
    "VARCHAR2":   StringType,
    "NVARCHAR2":  StringType,
    "VARCHAR":    StringType,
    "CHAR":       StringType,
    "NCHAR":      StringType,
    "CLOB":       StringType,
    "NCLOB":      StringType,
    "LONG":       StringType,
    "NUMBER":     IntegerType,   # refined to FloatType when scale > 0 (not detectable here)
    "INTEGER":    IntegerType,
    "INT":        IntegerType,
    "SMALLINT":   IntegerType,
    "FLOAT":      FloatType,
    "BINARY_FLOAT":  FloatType,
    "BINARY_DOUBLE": FloatType,
    "DECIMAL":    FloatType,
    "NUMERIC":    FloatType,
    "DATE":       DateType,
    "TIMESTAMP":  DateTimeType,
    "BOOLEAN":    BooleanType,
}

# ---------------------------------------------------------------------------
# Regex patterns for DDL parsing
# ---------------------------------------------------------------------------

# Match a full CREATE TABLE block (body between the outer parentheses)
_CREATE_TABLE_RE = re.compile(
    r"CREATE\s+TABLE\s+(\w+)\s*\((.*?)\)\s*;",
    re.IGNORECASE | re.DOTALL,
)

# Column with an identity (auto-increment) – skip these
_IDENTITY_RE = re.compile(r"GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY", re.IGNORECASE)

# Standalone FOREIGN KEY constraint line
_FK_CONSTRAINT_RE = re.compile(
    r"FOREIGN\s+KEY\s*\(\s*(\w+)\s*\)\s+REFERENCES\s+(\w+)\s*\(\s*\w+\s*\)",
    re.IGNORECASE,
)

# Regular column definition (name + type + optional size + optional NOT NULL + optional inline REFERENCES)
_COLUMN_RE = re.compile(
    r"^(\w+)\s+"                                          # column name
    r"(VARCHAR2|NVARCHAR2|VARCHAR|CHAR|NCHAR|CLOB|NCLOB"
    r"|LONG|NUMBER|INTEGER|INT|SMALLINT|FLOAT"
    r"|BINARY_FLOAT|BINARY_DOUBLE|DECIMAL|NUMERIC"
    r"|DATE|TIMESTAMP|BOOLEAN)"                           # type keyword
    r"(?:\s*\([^)]+\))?"                                  # optional (size,precision)
    r"(?:\s+NOT\s+NULL)?"                                 # optional NOT NULL
    r"(?:\s+REFERENCES\s+(\w+)\s*\(\s*\w+\s*\))?",       # optional inline FK
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _to_pascal(name: str) -> str:
    """Convert a snake_case or UPPER_CASE identifier to PascalCase.

    Examples:
        'author'             → 'Author'
        'book_item'          → 'BookItem'
        'ADMINISTRATIVE_STAFF' → 'AdministrativeStaff'
    """
    return "".join(word.capitalize() for word in name.lower().split("_"))


def _is_not_null(col_line: str) -> bool:
    """Return True if the column definition includes NOT NULL."""
    return bool(re.search(r"\bNOT\s+NULL\b", col_line, re.IGNORECASE))


# ---------------------------------------------------------------------------
# Core parse logic
# ---------------------------------------------------------------------------

def _collect_fk_columns(table_body: str) -> dict:
    """Return {fk_col_name: referenced_table_name} from a table body string.

    Two FK forms are handled:
      1. Standalone constraint: ``FOREIGN KEY (col) REFERENCES other_table(id)``
      2. Inline reference:     ``col_name NUMBER NOT NULL REFERENCES other_table(id)``
    """
    fk_map: dict = {}

    for line in table_body.splitlines():
        line = line.strip().rstrip(",")

        # 1. Standalone FOREIGN KEY constraint
        m = _FK_CONSTRAINT_RE.match(line)
        if m:
            fk_map[m.group(1).lower()] = m.group(2).lower()
            continue

        # 2. Inline column-level REFERENCES
        m2 = _COLUMN_RE.match(line)
        if m2 and m2.group(3):
            fk_map[m2.group(1).lower()] = m2.group(3).lower()

    return fk_map


def _parse_columns(table_body: str, fk_columns: set) -> set:
    """Parse column definitions from a table body and return a set of Properties.

    Skips:
      - IDENTITY (auto-increment) surrogate PK columns
      - Foreign key columns (those will become associations)
      - Standalone constraint lines (PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK)
    """
    properties: set = set()

    for line in table_body.splitlines():
        line = line.strip().rstrip(",")
        if not line or line.upper().startswith(("--", "/*")):
            continue

        # Skip IDENTITY primary key columns
        if _IDENTITY_RE.search(line):
            continue

        # Skip constraint keywords
        if re.match(r"(PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT)\b", line, re.IGNORECASE):
            continue

        m = _COLUMN_RE.match(line)
        if not m:
            continue

        col_name = m.group(1).lower()
        type_str = m.group(2).upper()

        # FK columns become associations, not attributes
        if col_name in fk_columns:
            continue

        buml_type = _ORACLE_TYPE_MAP.get(type_str, StringType)
        min_mult = 1 if _is_not_null(line) else 0

        properties.add(
            Property(
                name=col_name,
                type=buml_type,
                multiplicity=Multiplicity(min_mult, 1),
            )
        )

    return properties


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def oracle_apex_to_buml(ddl_path: str, module_name: str = None) -> DomainModel:
    """Parse an Oracle APEX DDL SQL file and return a BESSER B-UML DomainModel.

    This is the structural parser analogous to ``mendix_to_buml()`` and
    ``outsystems_to_buml()``.  It handles the DDL produced by Oracle APEX
    SQL Script exports (``script.sql``).

    Args:
        ddl_path:    Path to the DDL ``.sql`` file.
        module_name: Optional name for the resulting DomainModel; defaults to
                     the file stem.

    Returns:
        A populated ``DomainModel``, or ``None`` on a fatal error.
    """
    if not os.path.exists(ddl_path):
        print(f"❌ File not found: {ddl_path}")
        return None
    if os.path.getsize(ddl_path) == 0:
        print(f"❌ File is empty: {ddl_path}")
        return None

    with open(ddl_path, "r", encoding="utf-8") as fh:
        content = fh.read()

    name = module_name or os.path.splitext(os.path.basename(ddl_path))[0]
    domain_model = DomainModel(name=name)

    classes: dict = {}                      # table_name_lower → Class
    pending_fks: list = []                  # (from_table, fk_col, to_table)

    print(f"✅ Parsing Oracle APEX DDL: {os.path.basename(ddl_path)}")

    for match in _CREATE_TABLE_RE.finditer(content):
        table_raw = match.group(1)
        table_key = table_raw.lower()
        table_body = match.group(2)

        class_name = _to_pascal(table_key)

        # Collect FK columns first so we can skip them as plain attributes
        fk_map = _collect_fk_columns(table_body)          # {col → ref_table}
        fk_col_set = set(fk_map.keys())

        # Record FK edges for later association creation
        for fk_col, ref_table in fk_map.items():
            pending_fks.append((table_key, fk_col, ref_table))

        # Parse data attributes
        properties = _parse_columns(table_body, fk_col_set)

        cls = Class(name=class_name, attributes=properties)
        classes[table_key] = cls
        domain_model.types.add(cls)

        print(f"  Class '{class_name}': {sorted(p.name for p in properties)}")

    # ── Build BinaryAssociations from FK edges ─────────────────────────────
    print(f"  Building {len(pending_fks)} associations from FK constraints…")
    for idx, (from_table, _fk_col, to_table) in enumerate(pending_fks):
        if from_table not in classes or to_table not in classes:
            print(f"  ⚠ Skipping FK '{from_table}.{_fk_col}' → unknown table '{to_table}'")
            continue

        from_cls = classes[from_table]
        to_cls = classes[to_table]

        # Many side (from_table has the FK → it can have many rows per referenced row)
        end_many = Property(
            name=from_cls.name.lower(),
            type=from_cls,
            multiplicity=Multiplicity(0, "*"),
        )
        # One side (to_table is referenced → one row per FK value)
        end_one = Property(
            name=to_cls.name.lower(),
            type=to_cls,
            multiplicity=Multiplicity(0, 1),
        )

        assoc = BinaryAssociation(
            name=f"{from_cls.name}_{to_cls.name}",
            ends={end_many, end_one},
        )
        domain_model.associations.add(assoc)

    print(
        f"  Total: {len(classes)} classes, "
        f"{len(domain_model.associations)} associations"
    )
    return domain_model
