"""
Oracle APEX SQL Generator for BESSER B-UML domain models.

Produces Oracle-compatible DDL with:
- Safe PL/SQL DROP blocks (CASCADE CONSTRAINTS)
- NUMBER / VARCHAR2 / DATE / TIMESTAMP types
- NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY for root tables
- Class-table inheritance (shared PK/FK for subclasses)
- Named FK, UNIQUE, and CHECK constraints
- CHECK constraints for enumeration columns (no PostgreSQL CREATE TYPE AS ENUM)
- NUMBER(1) DEFAULT 0 with CHECK (col IN (0,1)) for booleans
- Oracle reserved-word renaming for table names
- Correct FK direction determined via besser structural_utils
- Topological table ordering respecting both inheritance and association FK deps
"""

import os
import re
from collections import defaultdict, deque
from besser.BUML.metamodel.structural import DomainModel, Class, Enumeration
from besser.generators.structural_utils import get_foreign_keys


def _camel_to_snake(name: str) -> str:
    """Convert camelCase / PascalCase / ALLCAPS to snake_case.

    Matches the same logic used by the APEX page template so that
    column names produced by both the DDL generator and the page
    generator are identical (e.g. familyName → family_name).
    """
    s1 = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

# ─────────────────────────────────────────────────────────────
# Oracle reserved words that clash as table / column identifiers
# ─────────────────────────────────────────────────────────────

ORACLE_RESERVED_TABLE_MAP = {
    'order':    'order_header',
    'user':     'app_user',
    'session':  'app_session',
    'comment':  'app_comment',
    'connect':  'app_connect',
    'resource': 'app_resource',
    'select':   'app_select',
    'level':    'app_level',
    'table':    'app_table',
    'lock':     'app_lock',
    'index':    'app_index',
    'file':     'app_file',
    'values':   'app_values',
}

ORACLE_RESERVED_COLUMN_MAP = {
    'comment':  'comment_text',
    'level':    'level_num',
    'number':   'num_value',
    'file':     'file_name',
    'lock':     'lock_flag',
}

# ─────────────────────────────────────────────────────────────
# BUML primitive type → Oracle SQL type
# ─────────────────────────────────────────────────────────────

ORACLE_TYPE_MAP = {
    'int':       'NUMBER',
    'str':       'VARCHAR2(100)',
    'float':     'NUMBER',
    'bool':      '__BOOL__',   # handled specially
    'time':      'TIMESTAMP',
    'date':      'DATE',
    'datetime':  'TIMESTAMP',
    'timedelta': 'NUMBER',
    'any':       'VARCHAR2(4000)',
}


class OracleApexSQLGenerator:
    """
    Generates Oracle APEX-compatible DDL from a BESSER B-UML DomainModel.

    Args:
        model (DomainModel): The B-UML domain model to generate DDL for.
        output_dir (str): Directory where the SQL file will be written.
        output_filename (str): Name of the output SQL file.
    """

    def __init__(self, model: DomainModel,
                 output_dir: str = None,
                 output_filename: str = "tables_oracle_apex.sql"):
        self.model = model
        self.output_dir = output_dir or os.path.join(os.getcwd(), "output")
        self.output_filename = output_filename

    # ── naming helpers ────────────────────────────────────────

    def _table_name(self, class_name: str) -> str:
        """Return the Oracle-safe table name for a class."""
        return ORACLE_RESERVED_TABLE_MAP.get(class_name.lower(), class_name)

    def _col_name(self, name: str) -> str:
        """Return an Oracle-safe, snake_case column name.

        Uses camel_to_snake so that DDL column names (e.g. family_name)
        match the names generated by the APEX page template.
        """
        snake = _camel_to_snake(name)
        return ORACLE_RESERVED_COLUMN_MAP.get(snake, snake)

    # ── model analysis helpers ────────────────────────────────

    def _get_enum_map(self) -> dict:
        """Return {enum_name: sorted_list_of_literal_names} for all enumerations."""
        result = {}
        for t in self.model.types:
            if isinstance(t, Enumeration):
                result[t.name] = sorted(lit.name for lit in t.literals)
        return result

    def _col_type(self, type_name: str, enum_map: dict) -> str:
        """Return Oracle SQL type string for a BUML type name."""
        if type_name in ORACLE_TYPE_MAP:
            return ORACLE_TYPE_MAP[type_name]
        if type_name in enum_map:
            max_len = max((len(v) for v in enum_map[type_name]), default=20)
            return f'VARCHAR2({max(max_len + 4, 20)})'
        return 'VARCHAR2(100)'

    def _find_parent(self, cls: Class):
        """Return the direct parent Class of cls, or None if it is a root class."""
        for gen in cls.generalizations:
            if gen.specific.name == cls.name:
                return gen.general
        return None

    def _compute_fk_columns(self, class_names: set):
        """
        Use besser's get_foreign_keys to determine the correct FK direction,
        then build per-class FK-column lists.

        Returns
        -------
        fk_map  : dict[class_name -> list[(col_name, ref_table_name, is_unique)]]
        nm_tables : list[(t1_name, t2_name, col1_name, col2_name)]
        """
        fk_map = {name: [] for name in class_names}
        nm_tables = []
        fkeys = get_foreign_keys(self.model)   # {assoc_name: [class_with_fk, ref_prop_name]}

        for assoc in self.model.associations:
            ends = list(assoc.ends)
            if len(ends) != 2:
                continue

            e0, e1 = ends[0], ends[1]
            n0, n1 = e0.type.name, e1.type.name
            if n0 not in class_names or n1 not in class_names:
                continue

            max0, max1 = e0.multiplicity.max, e1.multiplicity.max

            if max0 > 1 and max1 > 1:
                # N:M → junction table (sorted names for determinism)
                pair = sorted([
                    (self._table_name(n0), self._col_name(n0) + '_id'),
                    (self._table_name(n1), self._col_name(n1) + '_id'),
                ])
                nm_tables.append((pair[0][0], pair[1][0], pair[0][1], pair[1][1]))
                continue

            if assoc.name not in fkeys:
                continue

            class_with_fk, ref_prop_name = fkeys[assoc.name]
            if class_with_fk not in class_names:
                continue

            # The referenced table is the other class in the association
            ref_class = n1 if class_with_fk == n0 else n0
            ref_table = self._table_name(ref_class)

            # FK column name comes from the property name at the referenced end
            fk_col = self._col_name(ref_prop_name) + '_id'

            # 1:1 associations get a UNIQUE constraint on the FK column
            is_unique = (max0 == 1 and max1 == 1)

            fk_map[class_with_fk].append((fk_col, ref_table, is_unique))

        return fk_map, nm_tables

    def _topo_sort(self, classes: list, fk_map: dict) -> list:
        """
        Topologically sort class tables so that every referenced table is
        created *before* the table that references it.
        Handles both inheritance (parent before child) and FK dependencies.
        """
        class_by_name = {cls.name: cls for cls in classes}
        table_to_class = {self._table_name(cls.name): cls.name for cls in classes}

        # depends_on[A] = {B}  means table A must be created AFTER table B
        depends_on = defaultdict(set)

        for cls in classes:
            # inheritance
            parent = self._find_parent(cls)
            if parent and parent.name in class_by_name:
                depends_on[cls.name].add(parent.name)

            # FK association dependencies
            for _fk_col, ref_table, _unique in fk_map.get(cls.name, []):
                ref_cls_name = table_to_class.get(ref_table)
                if ref_cls_name and ref_cls_name != cls.name:
                    depends_on[cls.name].add(ref_cls_name)

        # Kahn's BFS topological sort
        in_degree = {cls.name: 0 for cls in classes}
        successors: dict = defaultdict(set)
        for name, deps in depends_on.items():
            for dep in deps:
                successors[dep].add(name)
                in_degree[name] += 1

        queue = deque(sorted(            # sorted for determinism
            (cls.name for cls in classes if in_degree[cls.name] == 0)
        ))
        ordered = []
        while queue:
            n = queue.popleft()
            ordered.append(class_by_name[n])
            for m in sorted(successors[n]):
                in_degree[m] -= 1
                if in_degree[m] == 0:
                    queue.append(m)

        # Fall back to original order if a cycle was detected
        return ordered if len(ordered) == len(classes) else classes

    # ── SQL generation ────────────────────────────────────────

    @staticmethod
    def _drop_view_block(name: str) -> str:
        """Drop a view with the given name, silently ignoring errors."""
        return (
            f"BEGIN\n"
            f"    EXECUTE IMMEDIATE 'DROP VIEW {name}';\n"
            f"EXCEPTION\n"
            f"    WHEN OTHERS THEN NULL;\n"
            f"END;\n"
            f"/"
        )

    @staticmethod
    def _drop_block(table: str) -> str:
        return (
            f"BEGIN\n"
            f"    EXECUTE IMMEDIATE 'DROP TABLE {table} CASCADE CONSTRAINTS';\n"
            f"EXCEPTION\n"
            f"    WHEN OTHERS THEN NULL;\n"
            f"END;\n"
            f"/"
        )

    def _drop_section(self, sorted_classes: list, nm_tables: list) -> list:
        """
        Build a SINGLE PL/SQL block that robustly cleans up all previous
        objects by:
          1. Dropping all referential (FK) constraints from relevant tables
             via user_constraints – catches stale named constraints that
             survived previous partial imports.
          2. Dropping any view that shares a name with a target table.
          3. Dropping all target tables with CASCADE CONSTRAINTS.
        """
        # Ordered list of table/object names to clean up (reverse of create order)
        names: list = []
        seen: set = set()
        for t1, t2, *_ in reversed(nm_tables):
            jname = f'{t1}_{t2}'
            if jname.upper() not in seen:
                names.append(jname)
                seen.add(jname.upper())
        for cls in reversed(sorted_classes):
            tname = self._table_name(cls.name)
            if tname.upper() not in seen:
                names.append(tname)
                seen.add(tname.upper())

        name_list = ', '.join(f"'{n.upper()}'" for n in names)

        out = []
        out.append('--------------------------------------------------')
        out.append('-- SAFE DROP')
        out.append('--------------------------------------------------')
        out.append('')
        out.append('BEGIN')
        out.append('    -- Step 1: drop all FK constraints on target tables')
        out.append('    --         (handles stale constraint names from previous imports)')
        out.append('    FOR c IN (')
        out.append('        SELECT constraint_name, table_name')
        out.append('        FROM   user_constraints')
        out.append(f'        WHERE  table_name IN ({name_list})')
        out.append("        AND    constraint_type = 'R'")
        out.append('    ) LOOP')
        out.append('        BEGIN')
        out.append("            EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name")
        out.append("                || ' DROP CONSTRAINT ' || c.constraint_name;")
        out.append('        EXCEPTION WHEN OTHERS THEN NULL;')
        out.append('        END;')
        out.append('    END LOOP;')
        out.append('')
        out.append('    -- Step 2: drop views that share a name with a target table')
        for n in names:
            out.append(f"    BEGIN EXECUTE IMMEDIATE 'DROP VIEW {n}'; EXCEPTION WHEN OTHERS THEN NULL; END;")
        out.append('')
        out.append('    -- Step 3: drop tables')
        for n in names:
            out.append(f"    BEGIN EXECUTE IMMEDIATE 'DROP TABLE {n} CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;")
        out.append('END;')
        out.append('/')
        out.append('')
        return out

    def generate(self):
        """
        Generate Oracle APEX DDL and write it to
        <output_dir>/<output_filename>.
        """
        os.makedirs(self.output_dir, exist_ok=True)
        file_path = os.path.join(self.output_dir, self.output_filename)

        enum_map = self._get_enum_map()
        classes = list(self.model.classes_sorted_by_inheritance())
        class_names = {cls.name for cls in classes}

        fk_map, nm_tables = self._compute_fk_columns(class_names)
        sorted_classes = self._topo_sort(classes, fk_map)

        out = []

        # ── 1. Safe DROP section (single PL/SQL block) ───────
        out.extend(self._drop_section(sorted_classes, nm_tables))

        # ── 2. CREATE TABLE for each class ───────────────────
        out.append('--------------------------------------------------')
        out.append('-- TABLES')
        out.append('--------------------------------------------------')
        out.append('')

        for cls in sorted_classes:
            tname = self._table_name(cls.name)
            parent = self._find_parent(cls)
            parent_tname = self._table_name(parent.name) if parent else None

            col_defs = []    # column definitions
            fk_cols = []     # FK columns from associations
            constraints = [] # table-level CONSTRAINT clauses

            # ── Primary key column ────────────────────────────
            # Every table (root AND subclass) gets its own identity PK.
            # Subclasses link to the parent via a separate FK column
            # (e.g. person_id → Person) instead of sharing the PK value.
            # This avoids ORA-02264 / ORA-02270 errors in Oracle APEX.
            col_defs.append(
                '    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
            )
            if parent is not None:
                parent_fk_col = f'{parent_tname.lower()}_id'
                fk_cols.append(f'    {parent_fk_col} NUMBER NOT NULL')
                # Anonymous FK: Oracle auto-generates a unique constraint name,
                # preventing ORA-02264 from stale named constraints in the schema.
                constraints.append(
                    f'    FOREIGN KEY ({parent_fk_col}) REFERENCES {parent_tname}(id)'
                )

            # ── Own attributes ────────────────────────────────
            for attr in sorted(cls.attributes, key=lambda a: a.name):
                cname = self._col_name(attr.name)
                type_name = attr.type.name
                not_null = '' if attr.is_optional else ' NOT NULL'

                if type_name == 'bool':
                    col_defs.append(
                        f'    {cname} NUMBER(1) DEFAULT 0{not_null}'
                    )
                    constraints.append(
                        f'    CONSTRAINT chk_{tname.lower()}_{cname}'
                        f' CHECK ({cname} IN (0, 1))'
                    )
                elif type_name in enum_map:
                    vals = enum_map[type_name]
                    max_len = max((len(v) for v in vals), default=20)
                    ctype = f'VARCHAR2({max(max_len + 4, 20)})'
                    col_defs.append(f'    {cname} {ctype}{not_null}')
                    vals_str = ', '.join(f"'{v}'" for v in vals)
                    constraints.append(
                        f'    CONSTRAINT chk_{tname.lower()}_{cname}'
                        f' CHECK ({cname} IN ({vals_str}))'
                    )
                else:
                    ctype = self._col_type(type_name, enum_map)
                    col_defs.append(f'    {cname} {ctype}{not_null}')

            # ── FK columns from associations (anonymous FKs) ──────────
            seen_fks: set = set()
            for fk_col, ref_table, is_unique in fk_map.get(cls.name, []):
                fk_key = (fk_col, ref_table)
                if fk_key in seen_fks:
                    continue
                seen_fks.add(fk_key)
                fk_cols.append(f'    {fk_col} NUMBER NOT NULL')
                # Anonymous FK avoids ORA-02264 name collisions with leftovers
                # from previous imports. Oracle generates a unique internal name.
                constraints.append(
                    f'    FOREIGN KEY ({fk_col}) REFERENCES {ref_table}(id)'
                )
                if is_unique:
                    constraints.append(
                        f'    CONSTRAINT uq_{tname.lower()}_{fk_col}'
                        f' UNIQUE ({fk_col})'
                    )

            # ── Assemble CREATE TABLE ─────────────────────────
            all_entries = col_defs + fk_cols + constraints
            out.append(f'-- {cls.name}')
            out.append(f'CREATE TABLE {tname} (')
            out.append(',\n'.join(all_entries))
            out.append(');')
            out.append('')

        # ── 3. Junction tables (N:M associations) ────────────
        if nm_tables:
            out.append('--------------------------------------------------')
            out.append('-- JUNCTION TABLES (N:M associations)')
            out.append('--------------------------------------------------')
            out.append('')
            seen_junctions: set = set()
            for t1, t2, col1, col2 in nm_tables:
                jname = f'{t1}_{t2}'
                if jname in seen_junctions:
                    continue
                seen_junctions.add(jname)
                jname_low = jname.lower()
                out.append(f'CREATE TABLE {jname} (')
                out.append(f'    {col1} NUMBER NOT NULL,')
                out.append(f'    {col2} NUMBER NOT NULL,')
                out.append(f'    PRIMARY KEY ({col1}, {col2}),')
                out.append(f'    FOREIGN KEY ({col1}) REFERENCES {t1}(id),')
                out.append(f'    FOREIGN KEY ({col2}) REFERENCES {t2}(id)')
                out.append(');')
                out.append('')

        content = '\n'.join(out)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Oracle APEX SQL generated: {file_path}")
